use_frameworks!

target 'MKTestViewPod_Example' do
  pod 'MKTestViewPod', :path => '../'

  target 'MKTestViewPod_Tests' do
	pod 'MKTestViewPod', :path => '../'

    pod 'FBSnapshotTestCase'
  end
end
